spring.application.name=project_newjeans
spring.config.import=optional:file:.env[.properties]
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/project_newjeans
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.datasource.username=${USER_NAME}
spring.datasource.password=${PASSWORD}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.resolve-lazily=true

#spring.servlet.multipart.max-file-size=5MB
#spring.servlet.multipart.max-request-size=20MB

spring.session.store-type=jdbc
spring.session.timeout=2m
spring.session.jdbc.initialize-schema=always

mail.username=${EMAIL}
mail.password=${SMTP_MAIL_CODE}

ip.api.url=http://ip-api.com
mail=${EMAIL}